import img1 from "./img/img1.jpg";
const data = {
  cardData: [
    {
      id: 1,
      name: "Samsung",
      price: 200,
      model: "S40",
      color: "red",
      image: img1,
    },
    {
      id: 2,
      name: "Samsung",
      price: 200,
      model: "S40",
      color: "black",
      image: img1,
    },
    {
      id: 3,
      name: "Samsung",
      price: 200,
      model: "S40",
      color: "gold",
      image: img1,
    },
    {
      id: 4,
      name: "Oppo",
      price: 400,
      model: "F12",
      color: "black",
      image: img1,
    },
    {
      id: 5,
      name: "Oppo",
      price: 400,
      model: "F12",
      color: "purple",
      image: img1,
    },
    {
      id: 6,
      name: "Redmi",
      price: 230,
      model: "R12",
      color: "black",
      image: img1,
    },
    {
      id: 7,
      name: "Redmi",
      price: 230,
      model: "R12",
      color: "red",
      image: img1,
    },
    {
      id: 8,
      name: "Iphone",
      price: 250,
      model: "13Pro Max",
      color: "black",
      image: img1,
    },
    {
      id: 9,
      name: "Iphone",
      price: 250,
      model: "13Pro Max",
      color: "blue",
      image: img1,
    },
    {
      id: 10,
      name: "Huawei",
      price: 300,
      model: "Mate 40",
      color: "black",
      image: img1,
    },
    {
      id: 11,
      name: "Huawei",
      price: 300,
      model: "Mate 40",
      color: "red",
      image: img1,
    },
  ],
};

export default data;
